name: Publish Maven Package

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set package version
      run: echo "::set-env name=PACKAGE_VERSION::${{ env.MAIN_VER }}.${{ github.run_number }}.$(date +"%y%m%d")"
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Publish to GitHub Packages Apache Maven
      run: |
        sed -i 's/${PACKAGE_VERSION}/${{ env.PACKAGE_VERSION }}/g' pom.xml
        mvn deploy -s settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        body: |
          Changes in this Release
          - Update Swagger Properties
        draft: false
        prerelease: false
